import { useEffect, useRef, useState, useCallback } from 'react'
import * as signalR from '@microsoft/signalr'
import { useQueryClient } from '@tanstack/react-query'
import { useNotificationContext } from '@/components/notifications/NotificationProvider'
import { PortalResponse } from '@/types/portal.types'
import { IncidentResponse } from '@/types/incident.types'
import { StatisticsResponse } from '@/types/statistics.types'
import { PagedResult } from '@/types/api.types'
