// <auto-generated />
using System;
using CentralCommand.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralCommand.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Author")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorAvatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IncidentId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IncidentId");

                    b.HasIndex("IncidentId1");

                    b.HasIndex("IncidentId", "CreatedAt");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.HealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpectedStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(200);

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("LastResponseTime")
                        .HasColumnType("float");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("GET");

                    b.Property<Guid>("PortalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PortalId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Timeout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5000);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LastChecked");

                    b.HasIndex("PortalId");

                    b.HasIndex("PortalId1");

                    b.HasIndex("Status");

                    b.HasIndex("PortalId", "IsEnabled");

                    b.ToTable("HealthChecks", (string)null);
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AffectedPortalIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedPortals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Assignee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssigneeEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DetectionSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstimatedResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalTicketRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ImpactedUsers")
                        .HasColumnType("int");

                    b.Property<string>("IncidentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostmortemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RelatedIncidents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReporterEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReporterName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RootCause")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Team")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timeline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("Team");

                    b.HasIndex("Type");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.MetricsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anomalies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Cpu")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ErrorRate")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("Memory")
                        .HasColumnType("float");

                    b.Property<Guid>("PortalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PortalId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("int");

                    b.Property<double>("ResponseTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Uptime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PortalId");

                    b.HasIndex("PortalId1");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PortalId", "Timestamp");

                    b.ToTable("MetricsHistory", (string)null);
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Portal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastIncident")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastStatusChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Maintainers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetricsHistoryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Team")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Environment");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.HasIndex("Owner");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("Team");

                    b.HasIndex("Status", "Environment");

                    b.ToTable("Portals", (string)null);
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Comment", b =>
                {
                    b.HasOne("CentralCommand.Core.Domain.Entities.Incident", null)
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralCommand.Core.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId1");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.HealthCheck", b =>
                {
                    b.HasOne("CentralCommand.Core.Domain.Entities.Portal", null)
                        .WithMany("HealthChecks")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralCommand.Core.Domain.Entities.Portal", "Portal")
                        .WithMany()
                        .HasForeignKey("PortalId1");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.MetricsHistory", b =>
                {
                    b.HasOne("CentralCommand.Core.Domain.Entities.Portal", null)
                        .WithMany("MetricsHistory")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralCommand.Core.Domain.Entities.Portal", "Portal")
                        .WithMany()
                        .HasForeignKey("PortalId1");

                    b.OwnsOne("CentralCommand.Core.Domain.ValueObjects.PortalMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("MetricsHistoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AverageLoadTime")
                                .HasColumnType("float");

                            b1.Property<double>("Cpu")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Cpu");

                            b1.Property<double>("ErrorRate")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_ErrorRate");

                            b1.Property<int>("Errors")
                                .HasColumnType("int")
                                .HasColumnName("Metrics_Errors");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Latency")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Latency");

                            b1.Property<double>("Memory")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Memory");

                            b1.Property<double>("PeakResponseTime")
                                .HasColumnType("float");

                            b1.Property<int>("Requests")
                                .HasColumnType("int")
                                .HasColumnName("Metrics_Requests");

                            b1.Property<int>("RequestsPerMinute")
                                .HasColumnType("int");

                            b1.Property<double>("ResponseTime")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_ResponseTime");

                            b1.Property<double>("Throughput")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Throughput");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("datetime2")
                                .HasColumnName("Metrics_Timestamp");

                            b1.Property<double>("Uptime")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Uptime");

                            b1.HasKey("MetricsHistoryId");

                            b1.ToTable("MetricsHistory");

                            b1.WithOwner()
                                .HasForeignKey("MetricsHistoryId");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Portal", b =>
                {
                    b.OwnsOne("CentralCommand.Core.Domain.ValueObjects.PortalMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("PortalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AverageLoadTime")
                                .HasColumnType("float");

                            b1.Property<double>("Cpu")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Cpu");

                            b1.Property<double>("ErrorRate")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_ErrorRate");

                            b1.Property<int>("Errors")
                                .HasColumnType("int")
                                .HasColumnName("Metrics_Errors");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Latency")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Latency");

                            b1.Property<double>("Memory")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Memory");

                            b1.Property<double>("PeakResponseTime")
                                .HasColumnType("float");

                            b1.Property<int>("Requests")
                                .HasColumnType("int")
                                .HasColumnName("Metrics_Requests");

                            b1.Property<int>("RequestsPerMinute")
                                .HasColumnType("int");

                            b1.Property<double>("ResponseTime")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_ResponseTime");

                            b1.Property<double>("Throughput")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Throughput");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("datetime2")
                                .HasColumnName("Metrics_Timestamp");

                            b1.Property<double>("Uptime")
                                .HasColumnType("float")
                                .HasColumnName("Metrics_Uptime");

                            b1.HasKey("PortalId");

                            b1.ToTable("Portals");

                            b1.WithOwner()
                                .HasForeignKey("PortalId");
                        });

                    b.OwnsOne("CentralCommand.Core.Domain.ValueObjects.PortalConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("PortalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("AlertThreshold")
                                .HasColumnType("float");

                            b1.Property<int>("CheckInterval")
                                .HasColumnType("int");

                            b1.Property<string>("CustomHeaders")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Config_CustomHeaders");

                            b1.Property<bool>("EnableAlerts")
                                .HasColumnType("bit")
                                .HasColumnName("Config_EnableAlerts");

                            b1.Property<bool>("EnableAutoRecovery")
                                .HasColumnType("bit")
                                .HasColumnName("Config_EnableAutoRecovery");

                            b1.Property<bool>("EnableMonitoring")
                                .HasColumnType("bit")
                                .HasColumnName("Config_EnableMonitoring");

                            b1.Property<string>("HealthCheckEndpoint")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Config_HealthCheckEndpoint");

                            b1.Property<int>("HealthCheckInterval")
                                .HasColumnType("int")
                                .HasColumnName("Config_HealthCheckInterval");

                            b1.Property<bool>("IsMonitoringEnabled")
                                .HasColumnType("bit");

                            b1.PrimitiveCollection<string>("NotificationEmails")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("RetryAttempts")
                                .HasColumnType("int")
                                .HasColumnName("Config_RetryAttempts");

                            b1.Property<int>("RetryCount")
                                .HasColumnType("int");

                            b1.Property<int>("RetryDelay")
                                .HasColumnType("int")
                                .HasColumnName("Config_RetryDelay");

                            b1.Property<int>("Timeout")
                                .HasColumnType("int")
                                .HasColumnName("Config_Timeout");

                            b1.HasKey("PortalId");

                            b1.ToTable("Portals");

                            b1.WithOwner()
                                .HasForeignKey("PortalId");
                        });

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CentralCommand.Core.Domain.Entities.Portal", b =>
                {
                    b.Navigation("HealthChecks");

                    b.Navigation("MetricsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
